apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-event-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-event
  template:
    metadata:
      labels:
        app: api-event
    spec:
      containers:
      - name: api-event
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 80
