apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-event-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api-event
        pathType: Prefix
        backend:
          service:
            name: api-event
            port:
              number: 80
